### ISSUE TITLE
Component crashes in Jest test

### ISSUE THREAD

**Issue by scolyer** [anthonyjgrove/react-google-login#131] opened 2017-11-24 03:00 UTC
I have a typescript react app that's using this component, and have a component test for my login component, which is composed of the react-google-login component.

When I run the test (just to see if the component will render) I get the following error:

TypeError: Cannot read property 'parentNode' of undefined.

**Comment by dnewcome** [comment] 2018-01-03 23:15
This seems to be caused by some logic that is intended to insert the Google login script tag before any existing tags in the DOM. If no script tags exist, `parentNode` is referenced on the zeroth item which is undefined.

I'm not sure of the original intent of this check so I left it and handled this edge case. If the logic is no longer needed I will remove it completely in my PR @anthonyjgrove . Thanks!

PR here:
https://github.com/anthonyjgrove/react-google-login/pull/143

**Comment by xxd3vin** [comment] 2018-01-23 10:55
Could mock a `script` tag to avoid this problem.

```
const head = document.getElementsByTagName('head')[0]
head.appendChild(document.createElement('script'))
```

**Comment by anthonyjgrove** [comment] 2018-03-12 02:17
should be fixed now

**Closed by anthonyjgrove** 2018-03-12 02:17 UTC
