### ISSUE TITLE
onAutoLoadFinished does not return the correct login status consistently

### ISSUE THREAD

**Issue by rhefner** [anthonyjgrove/react-google-login#340] opened 2020-05-19 19:39 UTC
### Usage

I made a few assumptions, maybe dangerously:
- That I can use the hook without adding the component provided by the library to my application (so, using it in a headless way)
- `onAutoLoadFinished` is supposed to return if the user is logged in or not. So, I set the context state telling the application if the user is logged in/not and the information I got from `localStorage` via `setResponse`'s corresponding state

How I'm using the login hook:
```
const initialState = {
  isLoggedIn: false,
  user: {},
  loginDetails: {}
};
...
...
const { signIn } = useGoogleLogin({
    clientId: config.auth.clientId,
    scope: 'profile',
    isSignedIn: true,
    cookiePolicy: 'single_host_origin',
    onSuccess: ({ profileObj: userInfo, ...loginDetails }: any) => {
      setLoggingIn(false);
      setResponse({ user: userInfo, loginDetails, isLoggedIn: true });
    },
    onFailure: (...args) => {
      setLoggingIn(false);
      setResponse({ ...initialState });
    },
    onAutoLoadFinished: (isLoggedIn) => {
      if (isLoggedIn) {
        setResponse({ ...response, isLoggedIn });
      } else {
        setResponse({ ...initialState });
      }
    }
  });
```
This is inside context that's wrapped the application. `setResponse` is a simple `React.useState` setter and preserves the response in `localStorage` (Using a reducer doesn't seem to matter with this issue). `setLoggingIn` is a `React.useState` setter as well that tells if the user is away logging in, so we can display a full page message.

### Issue
From what I've observed, `onAutoLoadFinished` does not return the correct login status across multiple page refreshes. I *think* I've traced down the issue to [google-api-javascript-client #399](https://github.com/google/google-api-javascript-client/issues/399) where in `use-google-login.js`, you're getting the google auth instance via `window.gapi.auth2.getAuthInstance()` in this block:
```
      window.gapi.load('auth2', () => {
        const GoogleAuth = window.gapi.auth2.getAuthInstance()
        if (!GoogleAuth) {
          window.gapi.auth2.init(params).then(
            res => {
              if (!unmounted) {
                setLoaded(true)
                const signedIn = isSignedIn && res.isSignedIn.get()
                onAutoLoadFinished(signedIn)
                if (signedIn) {
                  handleSigninSuccess(res.currentUser.get())
                }
              }
            },
            err => {
              setLoaded(true)
              onAutoLoadFinished(false)
              onFailure(err)
            }
          )
        } else if (isSignedIn && GoogleAuth.isSignedIn.get()) {
          setLoaded(true)
          onAutoLoadFinished(true)
          handleSigninSuccess(GoogleAuth.currentUser.get())
        } else if (!unmounted) {
          setLoaded(true)
          onAutoLoadFinished(false)
        }
      })
    })
```
But, it's not always ready and eventually goes down into:
```
        } else if (!unmounted) {
          setLoaded(true)
          onAutoLoadFinished(false)
        }
```
Adding a `setTimeout` inside the `!unmounted` condition above, like so:
```
        } else if (!unmounted) {
          setLoaded(true)
          onAutoLoadFinished(false)
          setTimeout(() => console.log('isSignedIn:', window.gapi.auth2.getAuthInstance().isSignedIn.get()), 5000);
        }
```
Returns the correct status, even though the `GoogleAuth` instance didn't. (take the above as pseudo code, as I added checks to make sure the instance was available and `isSignedIn` was as well.

### Proposed Fix
One fix proposed in the issue above is to wrap everything in `window.gapi.load`'s callback in `setTimeout(() => {...}, 1000)` and I've verified that works in my case. Also, the interesting part is that without any modifications to `node_modules/react-google-login/src/use-google-login.js` and just using `jsSrc: 'https://apis.google.com/js/api:client.js'` in the hook init works seemingly as well?

I find it strange, because `api:client.js` vs `api.js` in the API script source just changes `gapi.load("", ..` to `gapi.load("client", ..` and another area `"u":"https://apis.google.com/js/api.js"` to `"u":"https://apis.google.com/js/api:client.js"`

### ?
So, I wanted to check to see if anyone else is having a similar problem / am I the only one? And, if I'm using the library wrong and maybe there's something I'm just not doing to make it work properly without modifications?

_If it's the case I'm using the library wrong, then that's cool -- I just wanted to check either way. I definitely appreciate all the work you've put into this and am glad to leverage it!_

**Comment by stuckj** [comment] 2020-09-03 21:56
I haven't run into this issue, but while looking into how to use this library I was looking at the code you referred to here. My guess is that `useGoogleLogin` is being called more than once very quickly. Based on Google's docs here (https://developers.google.com/identity/sign-in/web/reference#auth_setup), ` window.gapi.auth2.init(params)` won't resolve until the `GoogleAuth` object is initialized. So, if `useGoogleLogin` is called rapidly in succession then the first will create the global `GoogleAuth` object, but it won't be initialized yet. The second will fall through the `if(!GoogleAuth)` call (since it's set, but not initialized), but you drop through since it's not initialized yet.

I don't know for sure if that's the issue (again, this was just from code inspection), but seems plausible.

If that is the problem then it probably needs to be fixed in the library. One solution could be to store the promose returned from `window.gapi.auth2.init` off in some state and add another else to check to see if the promise exists. If so, you can add another `then` onto that promise in the second `useGoogleLogin` call. Also, the promise would need to be cleared once the object is initialized.

DISCLAIMER: I haven't tested any of the above or repro'd. This is all just from code inspection. :)

**Comment by stuckj** [comment] 2020-09-03 23:46
It looks like `setLoaded` was intended to do this in the library code. But, I don't think it works because `GoogleUser` is set when `window.gapi.auth2.init` is called even though it's not immediately initialized.

**Comment by ranihorev** [comment] 2020-10-09 00:49
I had the same issue. Here is a PR that fixes that: https://github.com/anthonyjgrove/react-google-login/pull/381

**Closed** 2020-10-19 22:18 UTC
