### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by nilfric** [anthonyjgrove/react-google-login#49] opened 2017-02-14 11:23 UTC
When I try to install this as an npm module, it hangs. Here is the ouput of `npm i -ddd react-google-login`:

```
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'i',
npm verb cli   '-ddd',
npm verb cli   'react-google-login' ]
npm info using npm@4.1.2
npm info using node@v7.5.0
npm sill loadCurrentTree Starting
npm sill install loadCurrentTree
npm sill install readLocalPackageData
npm sill fetchPackageMetaData react-google-login
npm sill fetchNamedPackageData react-google-login
npm sill mapToRegistry name react-google-login
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: 'react-google-login',
npm sill mapToRegistry   scope: null,
npm sill mapToRegistry   escapedName: 'react-google-login',
npm sill mapToRegistry   name: 'react-google-login',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://registry.npmjs.org/react-google-login
npm verb request uri https://registry.npmjs.org/react-google-login
npm verb request no auth needed
npm info attempt registry request try #1 at 12:12:43
npm verb request id c61dda370c56c277
npm verb etag W/"58a0d936-12e17"
npm verb lastModified Sun, 12 Feb 2017 21:52:54 GMT
npm http request GET https://registry.npmjs.org/react-google-login
npm http 304 https://registry.npmjs.org/react-google-login
npm verb headers { date: 'Tue, 14 Feb 2017 11:12:42 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"58a0d936-12e17"',
npm verb headers   age: '224',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-hhn1528-HHN',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1487070762.663772,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm sill get cb [ 304,
npm sill get   { date: 'Tue, 14 Feb 2017 11:12:42 GMT',
npm sill get     via: '1.1 varnish',
npm sill get     'cache-control': 'max-age=300',
npm sill get     etag: 'W/"58a0d936-12e17"',
npm sill get     age: '224',
npm sill get     connection: 'keep-alive',
npm sill get     'x-served-by': 'cache-hhn1528-HHN',
npm sill get     'x-cache': 'HIT',
npm sill get     'x-cache-hits': '1',
npm sill get     'x-timer': 'S1487070762.663772,VS0,VE0',
npm sill get     vary: 'Accept-Encoding' } ]
npm verb etag https://registry.npmjs.org/react-google-login from cache
npm verb get saving react-google-login to C:\Users\myuser\AppData\Roaming\npm-cache\registry.npmjs.org\react-google-login\.cache.json
npm verb correctMkdir C:\Users\myuser\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm sill install normalizeTree
npm sill loadCurrentTree Finishing
npm sill loadIdealTree Starting
npm sill install loadIdealTree
npm sill cloneCurrentTree Starting
npm sill install cloneCurrentTreeToIdealTree
npm sill cloneCurrentTree Finishing
npm sill loadShrinkwrap Starting
npm sill install loadShrinkwrap
npm sill loadShrinkwrap Finishing
npm sill loadAllDepsIntoIdealTree Starting
npm sill install loadAllDepsIntoIdealTree
npm sill resolveWithNewModule react-google-login@2.8.1 checking installable status
npm sill cache add args [ 'react-google-login', null ]
npm verb cache add spec react-google-login
npm sill cache add parsed spec Result {
npm sill cache add   raw: 'react-google-login',
npm sill cache add   scope: null,
npm sill cache add   escapedName: 'react-google-login',
npm sill cache add   name: 'react-google-login',
npm sill cache add   rawSpec: '',
npm sill cache add   spec: 'latest',
npm sill cache add   type: 'tag' }
npm sill addNamed react-google-login@latest
npm verb addNamed "latest" is being treated as a dist-tag for react-google-login
npm info addNameTag [ 'react-google-login', 'latest' ]
npm sill mapToRegistry name react-google-login
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: 'react-google-login',
npm sill mapToRegistry   scope: null,
npm sill mapToRegistry   escapedName: 'react-google-login',
npm sill mapToRegistry   name: 'react-google-login',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://registry.npmjs.org/react-google-login
npm verb addNameTag registry:https://registry.npmjs.org/react-google-login not in flight; fetching
npm verb get https://registry.npmjs.org/react-google-login not expired, no request
npm sill addNameTag next cb for react-google-login with tag latest
npm sill addNamed react-google-login@2.8.1
npm verb addNamed "2.8.1" is a plain semver version for react-google-login
npm sill cache afterAdd react-google-login@2.8.1
npm verb afterAdd C:\Users\myuser\AppData\Roaming\npm-cache\react-google-login\2.8.1\package\package.json not in flight; writing
npm verb correctMkdir C:\Users\myuser\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm verb afterAdd C:\Users\myuser\AppData\Roaming\npm-cache\react-google-login\2.8.1\package\package.json written
npm sill fetchNamedPackageData @types/react
npm sill mapToRegistry name @types/react
npm sill mapToRegistry scope (from package name) @types
npm verb mapToRegistry no registry URL found in name for scope @types
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: '@types/react',
npm sill mapToRegistry   scope: '@types',
npm sill mapToRegistry   escapedName: '@types%2freact',
npm sill mapToRegistry   name: '@types/react',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://registry.npmjs.org/@types%2freact
npm verb request uri https://registry.npmjs.org/@types%2freact
npm verb request no auth needed
npm info attempt registry request try #1 at 12:12:43
npm verb etag "589e46af-d1c0"
npm http request GET https://registry.npmjs.org/@types%2freact
npm http 304 https://registry.npmjs.org/@types%2freact
npm verb headers { date: 'Tue, 14 Feb 2017 11:12:42 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=0',
npm verb headers   etag: '"589e46af-d1c0"',
npm verb headers   age: '0',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-hhn1528-HHN',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1487070762.911420,VS0,VE533',
npm verb headers   vary: 'Accept-Encoding' }
npm sill get cb [ 304,
npm sill get   { date: 'Tue, 14 Feb 2017 11:12:42 GMT',
npm sill get     via: '1.1 varnish',
npm sill get     'cache-control': 'max-age=0',
npm sill get     etag: '"589e46af-d1c0"',
npm sill get     age: '0',
npm sill get     connection: 'keep-alive',
npm sill get     'x-served-by': 'cache-hhn1528-HHN',
npm sill get     'x-cache': 'MISS',
npm sill get     'x-cache-hits': '0',
npm sill get     'x-timer': 'S1487070762.911420,VS0,VE533',
npm sill get     vary: 'Accept-Encoding' } ]
npm verb etag https://registry.npmjs.org/@types%2freact from cache
npm verb get saving @types/react to C:\Users\myuser\AppData\Roaming\npm-cache\registry.npmjs.org\_40types_252freact\.cache.json
npm verb correctMkdir C:\Users\myuser\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm sill pickManifestFromRegistryMetadata spec * tag latest versions [ '0.14.14-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.15-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.20-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.21-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.22-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.23-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.24-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.25-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.26-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.27',
npm sill pickManifestFromRegistryMetadata   '0.14.28',
npm sill pickManifestFromRegistryMetadata   '0.14.29',
npm sill pickManifestFromRegistryMetadata   '0.14.30',
npm sill pickManifestFromRegistryMetadata   '0.14.31',
npm sill pickManifestFromRegistryMetadata   '0.14.32',
npm sill pickManifestFromRegistryMetadata   '0.14.33',
npm sill pickManifestFromRegistryMetadata   '0.14.34',
npm sill pickManifestFromRegistryMetadata   '0.14.35',
npm sill pickManifestFromRegistryMetadata   '0.14.36',
npm sill pickManifestFromRegistryMetadata   '0.14.37',
npm sill pickManifestFromRegistryMetadata   '0.14.38',
npm sill pickManifestFromRegistryMetadata   '0.14.39',
npm sill pickManifestFromRegistryMetadata   '0.14.40',
npm sill pickManifestFromRegistryMetadata   '0.14.41',
npm sill pickManifestFromRegistryMetadata   '0.14.42',
npm sill pickManifestFromRegistryMetadata   '0.14.43',
npm sill pickManifestFromRegistryMetadata   '0.14.44',
npm sill pickManifestFromRegistryMetadata   '0.14.45',
npm sill pickManifestFromRegistryMetadata   '0.14.46',
npm sill pickManifestFromRegistryMetadata   '0.14.47',
npm sill pickManifestFromRegistryMetadata   '0.14.48',
npm sill pickManifestFromRegistryMetadata   '0.14.49',
npm sill pickManifestFromRegistryMetadata   '0.14.50',
npm sill pickManifestFromRegistryMetadata   '0.14.51',
npm sill pickManifestFromRegistryMetadata   '0.14.52',
npm sill pickManifestFromRegistryMetadata   '0.14.53',
npm sill pickManifestFromRegistryMetadata   '0.14.54',
npm sill pickManifestFromRegistryMetadata   '0.14.55',
npm sill pickManifestFromRegistryMetadata   '0.14.56',
npm sill pickManifestFromRegistryMetadata   '0.14.57',
npm sill pickManifestFromRegistryMetadata   '0.0.0',
npm sill pickManifestFromRegistryMetadata   '15.0.0',
npm sill pickManifestFromRegistryMetadata   '15.0.1',
npm sill pickManifestFromRegistryMetadata   '15.0.2',
npm sill pickManifestFromRegistryMetadata   '15.0.3',
npm sill pickManifestFromRegistryMetadata   '15.0.4',
npm sill pickManifestFromRegistryMetadata   '15.0.5',
npm sill pickManifestFromRegistryMetadata   '15.0.6',
npm sill pickManifestFromRegistryMetadata   '15.0.7',
npm sill pickManifestFromRegistryMetadata   '15.0.8',
npm sill pickManifestFromRegistryMetadata   '15.0.9' ]
npm sill resolveWithNewModule @types/react@15.0.9 checking installable status
npm sill cache add args [ '@types/react@*', null ]
npm verb cache add spec @types/react@*
npm sill cache add parsed spec Result {
npm sill cache add   raw: '@types/react@*',
npm sill cache add   scope: '@types',
npm sill cache add   escapedName: '@types%2freact',
npm sill cache add   name: '@types/react',
npm sill cache add   rawSpec: '*',
npm sill cache add   spec: '*',
npm sill cache add   type: 'range' }
npm sill addNamed @types/react@*
npm verb addNamed "*" is a valid semver range for @types/react
npm sill addNameRange { name: '@types/react', range: '*', hasData: false }
npm sill mapToRegistry name @types/react
npm sill mapToRegistry scope (from package name) @types
npm verb mapToRegistry no registry URL found in name for scope @types
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: '@types/react',
npm sill mapToRegistry   scope: '@types',
npm sill mapToRegistry   escapedName: '@types%2freact',
npm sill mapToRegistry   name: '@types/react',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://registry.npmjs.org/@types%2freact
npm verb addNameRange registry:https://registry.npmjs.org/@types%2freact not in flight; fetching
npm verb get https://registry.npmjs.org/@types%2freact not expired, no request
npm sill addNameRange number 2 { name: '@types/react', range: '*', hasData: true }
npm sill addNameRange versions [ '@types/react',
npm sill addNameRange   [ '0.14.14-alpha',
npm sill addNameRange     '0.14.15-alpha',
npm sill addNameRange     '0.14.20-alpha',
npm sill addNameRange     '0.14.21-alpha',
npm sill addNameRange     '0.14.22-alpha',
npm sill addNameRange     '0.14.23-alpha',
npm sill addNameRange     '0.14.24-alpha',
npm sill addNameRange     '0.14.25-alpha',
npm sill addNameRange     '0.14.26-alpha',
npm sill addNameRange     '0.14.27',
npm sill addNameRange     '0.14.28',
npm sill addNameRange     '0.14.29',
npm sill addNameRange     '0.14.30',
npm sill addNameRange     '0.14.31',
npm sill addNameRange     '0.14.32',
npm sill addNameRange     '0.14.33',
npm sill addNameRange     '0.14.34',
npm sill addNameRange     '0.14.35',
npm sill addNameRange     '0.14.36',
npm sill addNameRange     '0.14.37',
npm sill addNameRange     '0.14.38',
npm sill addNameRange     '0.14.39',
npm sill addNameRange     '0.14.40',
npm sill addNameRange     '0.14.41',
npm sill addNameRange     '0.14.42',
npm sill addNameRange     '0.14.43',
npm sill addNameRange     '0.14.44',
npm sill addNameRange     '0.14.45',
npm sill addNameRange     '0.14.46',
npm sill addNameRange     '0.14.47',
npm sill addNameRange     '0.14.48',
npm sill addNameRange     '0.14.49',
npm sill addNameRange     '0.14.50',
npm sill addNameRange     '0.14.51',
npm sill addNameRange     '0.14.52',
npm sill addNameRange     '0.14.53',
npm sill addNameRange     '0.14.54',
npm sill addNameRange     '0.14.55',
npm sill addNameRange     '0.14.56',
npm sill addNameRange     '0.14.57',
npm sill addNameRange     '0.0.0',
npm sill addNameRange     '15.0.0',
npm sill addNameRange     '15.0.1',
npm sill addNameRange     '15.0.2',
npm sill addNameRange     '15.0.3',
npm sill addNameRange     '15.0.4',
npm sill addNameRange     '15.0.5',
npm sill addNameRange     '15.0.6',
npm sill addNameRange     '15.0.7',
npm sill addNameRange     '15.0.8',
npm sill addNameRange     '15.0.9' ] ]
npm sill pickManifestFromRegistryMetadata spec * tag latest versions [ '0.14.14-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.15-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.20-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.21-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.22-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.23-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.24-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.25-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.26-alpha',
npm sill pickManifestFromRegistryMetadata   '0.14.27',
npm sill pickManifestFromRegistryMetadata   '0.14.28',
npm sill pickManifestFromRegistryMetadata   '0.14.29',
npm sill pickManifestFromRegistryMetadata   '0.14.30',
npm sill pickManifestFromRegistryMetadata   '0.14.31',
npm sill pickManifestFromRegistryMetadata   '0.14.32',
npm sill pickManifestFromRegistryMetadata   '0.14.33',
npm sill pickManifestFromRegistryMetadata   '0.14.34',
npm sill pickManifestFromRegistryMetadata   '0.14.35',
npm sill pickManifestFromRegistryMetadata   '0.14.36',
npm sill pickManifestFromRegistryMetadata   '0.14.37',
npm sill pickManifestFromRegistryMetadata   '0.14.38',
npm sill pickManifestFromRegistryMetadata   '0.14.39',
npm sill pickManifestFromRegistryMetadata   '0.14.40',
npm sill pickManifestFromRegistryMetadata   '0.14.41',
npm sill pickManifestFromRegistryMetadata   '0.14.42',
npm sill pickManifestFromRegistryMetadata   '0.14.43',
npm sill pickManifestFromRegistryMetadata   '0.14.44',
npm sill pickManifestFromRegistryMetadata   '0.14.45',
npm sill pickManifestFromRegistryMetadata   '0.14.46',
npm sill pickManifestFromRegistryMetadata   '0.14.47',
npm sill pickManifestFromRegistryMetadata   '0.14.48',
npm sill pickManifestFromRegistryMetadata   '0.14.49',
npm sill pickManifestFromRegistryMetadata   '0.14.50',
npm sill pickManifestFromRegistryMetadata   '0.14.51',
npm sill pickManifestFromRegistryMetadata   '0.14.52',
npm sill pickManifestFromRegistryMetadata   '0.14.53',
npm sill pickManifestFromRegistryMetadata   '0.14.54',
npm sill pickManifestFromRegistryMetadata   '0.14.55',
npm sill pickManifestFromRegistryMetadata   '0.14.56',
npm sill pickManifestFromRegistryMetadata   '0.14.57',
npm sill pickManifestFromRegistryMetadata   '0.0.0',
npm sill pickManifestFromRegistryMetadata   '15.0.0',
npm sill pickManifestFromRegistryMetadata   '15.0.1',
npm sill pickManifestFromRegistryMetadata   '15.0.2',
npm sill pickManifestFromRegistryMetadata   '15.0.3',
npm sill pickManifestFromRegistryMetadata   '15.0.4',
npm sill pickManifestFromRegistryMetadata   '15.0.5',
npm sill pickManifestFromRegistryMetadata   '15.0.6',
npm sill pickManifestFromRegistryMetadata   '15.0.7',
npm sill pickManifestFromRegistryMetadata   '15.0.8',
npm sill pickManifestFromRegistryMetadata   '15.0.9' ]
npm sill addNamed @types/react@latest
npm verb addNamed "latest" is being treated as a dist-tag for @types/react
npm info addNameTag [ '@types/react', 'latest' ]
npm sill mapToRegistry name @types/react
npm sill mapToRegistry scope (from package name) @types
npm verb mapToRegistry no registry URL found in name for scope @types
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: '@types/react',
npm sill mapToRegistry   scope: '@types',
npm sill mapToRegistry   escapedName: '@types%2freact',
npm sill mapToRegistry   name: '@types/react',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://registry.npmjs.org/@types%2freact
npm verb addNameTag registry:https://registry.npmjs.org/@types%2freact already in flight; waiting
npm sill addNameTag next cb for @types/react with tag latest
npm sill addNamed @types/react@15.0.9
npm verb addNamed "15.0.9" is a plain semver version for @types/react
npm sill cache afterAdd @types/react@15.0.9
npm verb afterAdd C:\Users\myuser\AppData\Roaming\npm-cache\@types\react\15.0.9\package\package.json not in flight; writing
npm verb correctMkdir C:\Users\myuser\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm verb afterAdd C:\Users\myuser\AppData\Roaming\npm-cache\@types\react\15.0.9\package\package.json written
npm sill loadAllDepsIntoIdealTree Finishing
npm sill loadIdealTree Finishing
npm sill currentTree react-google-login-bug@1.0.0
npm sill idealTree react-google-login-bug@1.0.0
npm sill idealTree +-- @types/react@15.0.9
npm sill idealTree `-- react-google-login@2.8.1
npm sill generateActionsToTake Starting
npm sill install generateActionsToTake
npm sill generateActionsToTake Finishing
npm sill diffTrees action count 2
npm sill diffTrees add @types/react@15.0.9
npm sill diffTrees add react-google-login@2.8.1
npm sill decomposeActions action count 16
npm sill decomposeActions fetch @types/react@15.0.9
npm sill decomposeActions extract @types/react@15.0.9
npm sill decomposeActions test @types/react@15.0.9
npm sill decomposeActions preinstall @types/react@15.0.9
npm sill decomposeActions build @types/react@15.0.9
npm sill decomposeActions install @types/react@15.0.9
npm sill decomposeActions postinstall @types/react@15.0.9
npm sill decomposeActions finalize @types/react@15.0.9
npm sill decomposeActions fetch react-google-login@2.8.1
npm sill decomposeActions extract react-google-login@2.8.1
npm sill decomposeActions test react-google-login@2.8.1
npm sill decomposeActions preinstall react-google-login@2.8.1
npm sill decomposeActions build react-google-login@2.8.1
npm sill decomposeActions install react-google-login@2.8.1
npm sill decomposeActions postinstall react-google-login@2.8.1
npm sill decomposeActions finalize react-google-login@2.8.1
npm sill runTopLevelLifecycles Starting
npm sill executeActions Starting
npm sill install executeActions
npm sill doSerial global-install 0
npm sill doParallel fetch 2
npm verb correctMkdir C:\Users\myuser\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb lock using C:\Users\myuser\AppData\Roaming\npm-cache\_locks\staging-0ec845a5045f16a0.lock for C:\Users\myuser\react-google-login-bug\node_modules\.staging
npm sill doParallel extract 2
npm sill extract @types/react@15.0.9
npm sill extract react-google-login@2.8.1
npm verb unbuild node_modules\.staging\@types\react-792e2059
npm verb unbuild node_modules\.staging\react-google-login-bb8ed12e
npm sill gentlyRm C:\Users\myuser\react-google-login-bug\node_modules\.staging\@types\react-792e2059 is being purged from base C:\Users\myuser\react-google-login-bug
npm verb gentlyRm don't care about contents; nuking C:\Users\myuser\react-google-login-bug\node_modules\.staging\@types\react-792e2059
npm verb tar unpack C:\Users\myuser\AppData\Roaming\npm-cache\@types\react\15.0.9\package.tgz
npm verb tar unpacking to C:\Users\myuser\react-google-login-bug\node_modules\.staging\@types\react-792e2059
npm sill gentlyRm C:\Users\myuser\react-google-login-bug\node_modules\.staging\@types\react-792e2059 is being purged
npm verb gentlyRm don't care about contents; nuking C:\Users\myuser\react-google-login-bug\node_modules\.staging\@types\react-792e2059
npm sill gunzTarPerm modes [ '777', '666' ]
npm sill gentlyRm C:\Users\myuser\react-google-login-bug\node_modules\.staging\react-google-login-bb8ed12e is being purged from base C:\Users\myuser\react-google-login-bug
npm verb gentlyRm don't care about contents; nuking C:\Users\myuser\react-google-login-bug\node_modules\.staging\react-google-login-bb8ed12e
npm verb tar unpack C:\Users\myuser\AppData\Roaming\npm-cache\react-google-login\2.8.1\package.tgz
npm verb tar unpacking to C:\Users\myuser\react-google-login-bug\node_modules\.staging\react-google-login-bb8ed12e
npm sill gentlyRm C:\Users\myuser\react-google-login-bug\node_modules\.staging\react-google-login-bb8ed12e is being purged
npm verb gentlyRm don't care about contents; nuking C:\Users\myuser\react-google-login-bug\node_modules\.staging\react-google-login-bb8ed12e
npm sill gunzTarPerm modes [ '777', '666' ]
npm sill gunzTarPerm extractEntry README.md
npm sill gunzTarPerm extractEntry package.json
npm sill gunzTarPerm modified mode [ 'package.json', 420, 438 ]
npm sill gunzTarPerm extractEntry index.d.ts
npm sill gunzTarPerm extractEntry package.json
npm sill gunzTarPerm extractEntry types-metadata.json
npm sill gunzTarPerm extractEntry .npmignore
npm sill gunzTarPerm modified mode [ '.npmignore', 420, 438 ]
npm sill gunzTarPerm extractEntry README.md
npm sill gunzTarPerm modified mode [ 'README.md', 420, 438 ]
npm sill gunzTarPerm extractEntry webpack.config.dist.js
npm sill gunzTarPerm modified mode [ 'webpack.config.dist.js', 493, 511 ]
npm sill gunzTarPerm extractEntry webpack.config.dev.js
npm sill gunzTarPerm modified mode [ 'webpack.config.dev.js', 420, 438 ]
npm sill gunzTarPerm extractEntry demo/index.js
npm sill gunzTarPerm modified mode [ 'demo/index.js', 420, 438 ]
npm sill gunzTarPerm extractEntry demo/index.html
npm sill gunzTarPerm modified mode [ 'demo/index.html', 420, 438 ]
npm sill gunzTarPerm extractEntry dist/google-login.js
npm sill gunzTarPerm modified mode [ 'dist/google-login.js', 420, 438 ]
npm sill gunzTarPerm extractEntry dist/google-login.js.map
npm sill gunzTarPerm modified mode [ 'dist/google-login.js.map', 420, 438 ]
npm sill gunzTarPerm extractEntry .eslintrc
npm sill gunzTarPerm modified mode [ '.eslintrc', 420, 438 ]
npm sill gunzTarPerm extractEntry .c9/.nakignore
npm sill gunzTarPerm modified mode [ '.c9/.nakignore', 420, 438 ]
npm sill gunzTarPerm extractEntry .c9/metadata/preview-https:/react-google-login-th3legend.c9users.io
npm sill gunzTarPerm modified mode [ '.c9/metadata/preview-https:/react-google-login-th3legend.c9users.io',
npm sill gunzTarPerm   420,
npm sill gunzTarPerm   438 ]
npm sill gunzTarPerm extractEntry .c9/metadata/tab0
npm sill gunzTarPerm modified mode [ '.c9/metadata/tab0', 420, 438 ]
npm sill gunzTarPerm extractEntry .c9/metadata/workspace/package.json
npm sill gunzTarPerm modified mode [ '.c9/metadata/workspace/package.json', 420, 438 ]
npm sill gunzTarPerm extractEntry .c9/metadata/workspace/README.md
npm sill gunzTarPerm modified mode [ '.c9/metadata/workspace/README.md', 420, 438 ]
npm sill gunzTarPerm extractEntry .c9/metadata/workspace/webpack.config.dev.js
npm sill gunzTarPerm modified mode [ '.c9/metadata/workspace/webpack.config.dev.js', 420, 438 ]
npm sill gunzTarPerm extractEntry .c9/metadata/workspace/.eslintrc
npm sill gunzTarPerm modified mode [ '.c9/metadata/workspace/.eslintrc', 420, 438 ]
npm sill gunzTarPerm extractEntry .c9/metadata/workspace/demo/index.js
npm sill gunzTarPerm modified mode [ '.c9/metadata/workspace/demo/index.js', 420, 438 ]
npm sill gentlyRm C:\Users\myuser\react-google-login-bug\node_modules\.staging\@types\react-792e2059\node_modules is being purged
npm verb gentlyRm don't care about contents; nuking C:\Users\myuser\react-google-login-bug\node_modules\.staging\@types\react-792e2059\node_modules
npm sill gunzTarPerm extractEntry .c9/metadata/workspace/index.d.ts
npm sill gunzTarPerm modified mode [ '.c9/metadata/workspace/index.d.ts', 420, 438 ]
npm sill gunzTarPerm extractEntry .c9/metadata/workspace/src/index.js
npm sill gunzTarPerm modified mode [ '.c9/metadata/workspace/src/index.js', 420, 438 ]
npm sill gunzTarPerm extractEntry .c9/metadata/workspace/test/google_test.js
npm sill gunzTarPerm modified mode [ '.c9/metadata/workspace/test/google_test.js', 420, 438 ]
npm sill gunzTarPerm extractEntry .c9/project.settings
npm sill gunzTarPerm modified mode [ '.c9/project.settings', 420, 438 ]
[              ....] | extract:@types/react: sill gunzTarPerm modified mode [ '.c9/project.settings', 420, 438 ]
```

**Comment by ddiviacchi** [comment] 2017-02-15 15:04
My Install also hangs while trying to install.

**Comment by anthonyjgrove** [comment] 2017-02-18 03:13
What OS are you tying to install it on?

**Comment by anthonyjgrove** [comment] 2017-02-18 03:17
duplicate of issue #43

**Comment by ddiviacchi** [comment] 2017-02-18 11:39
Windows 8.1 enterprise

**Comment by anthonyjgrove** [comment] 2017-03-15 02:38
I do not have access to a Windows 8.1 machine. If you figure it out please submit a PR. Sorry I cannot be more help.

**Closed** 2017-03-25 14:14 UTC
