### ISSUE TITLE
Migration from Google Sign-In JavaScript Platform Library

### ISSUE THREAD

**Issue by b-meet** [anthonyjgrove/react-google-login#518] opened 2022-05-20 05:09 UTC
Hey pals,
I used this package for a new project and when I clicked on login button the onFailure function was triggered which gave me an error  _"You have created a new client application that uses libraries for user authentication or authorization that will soon be deprecated. New clients must use the new libraries instead; existing clients must also migrate before these libraries are deprecated."_

![image](https://user-images.githubusercontent.com/82386196/169453589-ecb23ae6-369c-46ce-8805-a8fd18ca02c2.png)

So after searching on internet, I got to know that google is going to fully [retire ](https://developers.google.com/identity)the Google Sign-In JavaScript Platform Library from **March 31, 2023**. 

So I would like to remind you to plan for a migration.

Beginning from **April 30th, 2022** new applications must use the Google Identity Services library, existing apps may continue using the Platform Library **until the deprecation date**.

You can visit this link to know about the [migration](https://developers.google.com/identity/gsi/web/guides/migration)

**Comment by srijanshetty** [comment] 2022-05-20 09:09
+1 Facing the same issue

**Comment by srijanshetty** [comment] 2022-05-20 09:10
Duplicate of #502, please close.

**Closed** 2022-05-21 18:05 UTC
