### ISSUE TITLE
Button Style

### ISSUE THREAD

**Issue by 0xcaff** [anthonyjgrove/react-google-login#184] opened 2018-09-04 04:17 UTC
When I create an instance of the component

```
        <GoogleLogin
          clientId={clientId}
          onSuccess={console.log}
          onFailure={console.log}
        />
```

I see this:

![image](https://user-images.githubusercontent.com/3277097/45009702-a53f0400-afd7-11e8-9adf-bf855d3fed26.png)

Shouldn't I be seeing a sign in button like the one in the picture below?

![image](https://user-images.githubusercontent.com/3277097/45009712-b4be4d00-afd7-11e8-8685-6eb21ad6ab9f.png)

Or does this library not handle styling the button? I think this should be made clear in the readme or a demo.

**Comment by anthonyjgrove** [comment] 2018-09-07 19:36
Closing as it is duplicate of #147  Open PR for this issue: #180 hope to have this taken care of soon.

**Closed by anthonyjgrove** 2018-09-07 19:36 UTC

**Comment by dagumak** [comment] 2018-09-30 08:43
Wouldn't it be better to slim-down this library with the styling and class stuff and use this library?
https://github.com/prescottprue/react-google-button

For example:

```
<GoogleLogin
              clientId="REMOVED"
              onSuccess={this.authenticateProvider}
              style={{
                border: 'none',
                background: 'none',
                padding: 0,
                margin: 0 
              }}
              onFailure={(response) => console.log(response)}>
              <GoogleButton />
            </GoogleLogin>
```

**Comment by luckypatidar** [comment] 2021-03-08 12:32
use this
const inStyle = { background: "#000000"};
<GoogleLogin
    clientId="658977310896-knrl3gka66fldh83dao2rhgbblmd4un9.apps.googleusercontent.com"
    render={renderProps => (
      <button onClick={renderProps.onClick} style={inStyle}>Google button</button>
    )}
    buttonText="Login"
    onSuccess={responseGoogle}
    onFailure={responseGoogle}
/>

**Comment by jaiman25400** [comment] 2021-08-02 10:17
Hey I want add <Fcgoogle> Icon to this code and when I clicked to signIn to Google should PopUp.
Any Ideas would be Helpful
