### ISSUE TITLE
@types/react is not in the npm registry

### ISSUE THREAD

**Issue by ajeyak** [anthonyjgrove/react-google-login#68] opened 2017-04-24 07:56 UTC
Im trying to install this component, but I get the error:

npm ERR! node v4.1.1
npm ERR! npm  v4.0.2
npm ERR! code E404

npm ERR! 404 no such package available : @types/react
npm ERR! 404
npm ERR! 404  '@types/react' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'react-google-login'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

I tried installing "@types/react" with the command: 

npm install "@types/react" --save

but no luck. 

How do I get rid of this problem?

**Comment by arunshan** [comment] 2017-05-11 17:19
@ajeyak Any updates on it? I am facing the same issue

**Comment by aaio** [comment] 2017-06-20 18:57
@arunshan @ajeyak which OS and version of npm (`npm --version`) are you guys using? no errors with npm 5.0.3 here.

**Comment by aaio** [comment] 2017-06-26 20:52
Marking as closed -- cannot reproduce.

**Closed by aaio** 2017-06-26 20:52 UTC

**Comment by ZelvaJan** [comment] 2017-06-29 08:48
Error is caused due to using scoped dependencies. Same issue can be found in another libraries. For example: https://github.com/storybooks/storybook/issues/15
Quick workaround is to use `npm set registry https://registry.npmjs.org/` before project build.
